//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectExample.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cadidate
    {
        public int id_candidate { get; set; }
        public string code_cadi { get; set; }
        public Nullable<int> id_vanacy { get; set; }
        public string Name_cadidate { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public Nullable<int> status { get; set; }
        public string link_cv { get; set; }
    
        public virtual Vancacy Vancacy { get; set; }
    }
}
