//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectExample.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HR_projectEntities : DbContext
    {
        public HR_projectEntities()
            : base("name=HR_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Cadidate> Cadidates { get; set; }
        public virtual DbSet<Candidate_Employe> Candidate_Employe { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<infoUser> infoUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vancacy> Vancacies { get; set; }
    }
}
