//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectExample.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vancacy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vancacy()
        {
            this.Cadidates = new HashSet<Cadidate>();
        }
    
        public int id { get; set; }
        public int id_emp { get; set; }
        public string username { get; set; }
        public string title_job_position { get; set; }
        public string decription { get; set; }
        public int status { get; set; }
        public Nullable<int> quantity { get; set; }
        public System.DateTime date_submitted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cadidate> Cadidates { get; set; }
        public virtual Employee Employee { get; set; }


    }
}
