//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectExample.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Employe
    {
        public int id_CadiEmp { get; set; }
        public Nullable<int> id_emp { get; set; }
        public string code_cadi { get; set; }
        public Nullable<System.DateTime> DateTime_start { get; set; }
        public Nullable<System.DateTime> DateTime_end { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
