//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectExample.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HR_projectEntities2 : DbContext
    {
        public HR_projectEntities2()
            : base("name=HR_projectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Cadidate> Cadidates { get; set; }
        public virtual DbSet<Candidate_Employe> Candidate_Employe { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<infoUser> infoUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vancacy> Vancacies { get; set; }
    
        public virtual int sp_BuoiPhongVan(Nullable<int> id_emp1, Nullable<int> id_emp2, Nullable<int> id_emp3, string code_cadi, Nullable<System.DateTime> dtime_start, Nullable<System.DateTime> dtime_end)
        {
            var id_emp1Parameter = id_emp1.HasValue ?
                new ObjectParameter("id_emp1", id_emp1) :
                new ObjectParameter("id_emp1", typeof(int));
    
            var id_emp2Parameter = id_emp2.HasValue ?
                new ObjectParameter("id_emp2", id_emp2) :
                new ObjectParameter("id_emp2", typeof(int));
    
            var id_emp3Parameter = id_emp3.HasValue ?
                new ObjectParameter("id_emp3", id_emp3) :
                new ObjectParameter("id_emp3", typeof(int));
    
            var code_cadiParameter = code_cadi != null ?
                new ObjectParameter("code_cadi", code_cadi) :
                new ObjectParameter("code_cadi", typeof(string));
    
            var dtime_startParameter = dtime_start.HasValue ?
                new ObjectParameter("Dtime_start", dtime_start) :
                new ObjectParameter("Dtime_start", typeof(System.DateTime));
    
            var dtime_endParameter = dtime_end.HasValue ?
                new ObjectParameter("Dtime_end", dtime_end) :
                new ObjectParameter("Dtime_end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BuoiPhongVan", id_emp1Parameter, id_emp2Parameter, id_emp3Parameter, code_cadiParameter, dtime_startParameter, dtime_endParameter);
        }
    
        public virtual ObjectResult<sp_showInterViews_Result> sp_showInterViews(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_showInterViews_Result>("sp_showInterViews", usernameParameter);
        }
    
        public virtual ObjectResult<sp_XemDeXuatPhongVan1_Result> sp_XemDeXuatPhongVan1(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemDeXuatPhongVan1_Result>("sp_XemDeXuatPhongVan1", usernameParameter);
        }
    }
}
